services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

networks:
  default:
    external:
      name: DEMOSPDN

